### ISSUE TITLE
Add info about fork syncing

### ISSUE THREAD

**Issue by gtema** [opentelekomcloud-docs/docs_on_docs#17]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork is helpful to get required steps in order to synchronize local fork with remote upstream

**Comment by lourieder** [comment]
Thanks for bringing it up - on the doc it states "People with write access for a forked repository can sync the fork to the upstream repository."  how does that affect us? It wouldn't make sense to document it if the end user can't use it in the end.

**Comment by gtema** [comment]
well, we definitely need to make people aware of the procedure as such (at least by including link). Maybe it is even sufficient to really only link from our docs to this article and let people go through it. On the over side also having snippet is also good as (TL;DR):
```
Configure upstream remote
=====================

.. code-block:: bash
   $ git remote add upstream https://github.com/ORIGINAL_OWNER/ORIGINAL_REPOSITORY.git

Sync
====

.. code-block:: bash

   $ git fetch upstream
   $ git checkout main
   $ git merge upstream/main
```

**Comment by gtema** [comment]
the point is - regular beginners do not know how to sync their forks, they may not even properly understand what it is. We need to catch them up

**Comment by lourieder** [comment]
yes right.
I think it will be a good idea to have a seperate document on using github/git. Because I think there are more processes that should be described

**Comment by vladimirhasko** [comment]
completed
