### ISSUE TITLE
Further consideration for documentation update

### ISSUE THREAD

**Issue by vladimirhasko** [opentelekomcloud-docs/docs_on_docs#2]
1. description of new structure of document
	- rst files
	- macros
	- links
	- definition of references to internal/external links
	- references using ref anchors
2. Table construction problem
	- how to properly tables
	- nightmare to edit in standard notepad
3. Define proper WSWG tool for RST editing

**Comment by lourieder** [comment]
Thanks for bringing it up. I will handle your Issue right away

**Comment by vladimirhasko** [comment]
completed
